---
variables:
  GIT_DEPTH: 10
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

test:
  image: rust:alpine
  stage: test
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo test
  cache:
    paths:
      - .cargo

rustfmt:
  image: rust:alpine
  stage: test
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add rustfmt
  script:
    - rustfmt --check sestoft1996/src/lib.rs
  cache:
    paths:
      - .cargo
